# Generated by Django 5.0.2 on 2025-11-02 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('activity', '0001_initial'), ('activity', '0002_student_notes_alter_student_facebook_profile'), ('activity', '0003_alter_enrollment_status'), ('activity', '0004_activity_closed'), ('activity', '0005_session_closed'), ('activity', '0006_alter_activity_options'), ('activity', '0007_alter_activity_options'), ('activity', '0008_remove_organization_contact_email_contact'), ('activity', '0009_alter_activity_day_of_week'), ('activity', '0010_organization_is_deleted'), ('activity', '0011_student_active'), ('activity', '0012_alter_student_emergency_contact_name_and_more'), ('activity', '0013_student_rochester')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Zumba', 'Zumba'), ('Pound', 'Pound')], max_length=20)),
                ('day_of_week', models.CharField(max_length=10)),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('facebook_profile', models.URLField(blank=True, null=True, verbose_name='Facebook profile URL')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, max_length=2048, null=True)),
                ('active', models.BooleanField(default=True, help_text='Is this student currently active?')),
                ('rochester', models.BooleanField(default=False, help_text='Rochester Resident')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='activity.activity')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='activity.organization')),
                ('closed', models.BooleanField(default=False, help_text='Mark this session as closed when it has completed.')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='activity.session'),
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('scheduled', 'Scheduled')], max_length=10)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='activity.meeting')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='activity.student')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('waiting', 'Waiting List'), ('dropped', 'Dropped'), ('not_enrolled', 'Not Enrolled')], default='active')),
                ('date_enrolled', models.DateField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='activity.activity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='activity.student')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='closed',
            field=models.BooleanField(default=False, help_text='Mark this activity as closed when it has completed.'),
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='activity.organization')),
            ],
        ),
        migrations.AlterField(
            model_name='activity',
            name='day_of_week',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10),
        ),
    ]
