# Generated by Django 5.0.2 on 2025-10-31 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='notes',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='facebook_profile',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook profile URL'),
        ),
    ]
