# Generated by Django 5.0.2 on 2025-10-31 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_student_notes_alter_student_facebook_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('waiting', 'Waiting List'), ('dropped', 'Dropped'), ('not_enrolled', 'Not Enrolled')], default='active'),
        ),
    ]
