# Generated by Django 5.0.2 on 2025-11-01 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_alter_enrollment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='closed',
            field=models.BooleanField(default=False, help_text='Mark this activity as closed when it has completed.'),
        ),
    ]
