# Generated by Django 5.0.2 on 2025-11-01 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_activity_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='closed',
            field=models.BooleanField(default=False, help_text='Mark this session as closed when it has completed.'),
        ),
    ]
