# Generated by Django 5.0.2 on 2025-11-01 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_session_closed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={},
        ),
    ]
