# Generated by Django 5.0.2 on 2025-11-01 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_alter_activity_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
    ]
