# Generated by Django 5.0.2 on 2025-11-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0010_organization_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='active',
            field=models.BooleanField(default=True, help_text='Is this student currently active?'),
        ),
    ]
