# Generated by Django 5.0.2 on 2025-11-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0011_student_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
