# Generated by Django 5.0.2 on 2025-11-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0012_alter_student_emergency_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rochester',
            field=models.BooleanField(default=False, help_text='Rochester Resident'),
        ),
    ]
