# Generated by Django 5.0.2 on 2025-11-04 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial_squashed_0013_student_rochester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('Zumba', 'Zumba'), ('Pound', 'Pound'), ('Zumba Gold', 'Zumba Gold'), ('Aqua Zumba', 'Aqua Zumba'), ('Cardio Drumming', 'Cardio Drumming')], max_length=20),
        ),
    ]
