# Generated by Django 5.2.8 on 2025-11-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0015_contact_office_and_cell_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('unexpected_absence', 'Unexpected Absence'), ('expected_absence', 'Expected Absence'), ('scheduled', 'Scheduled')], max_length=20),
        ),
    ]
