# Generated by Django 5.2.8 on 2025-11-09 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0016_alter_attendancerecord_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meeting',
            unique_together={('activity', 'date')},
        ),
    ]
