# Generated by Django 5.2.8 on 2025-11-09 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0017_add_meeting_unique_constrai'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, help_text='Optional reason for cancellation', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellations', to='activity.activity')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('activity', 'date')},
            },
        ),
    ]
