# Generated by Django 5.2.8 on 2025-11-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0019_alter_student_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the location (e.g., 'Community Center Gym')", max_length=100)),
                ('address', models.CharField(blank=True, help_text='Physical address of the location', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Additional details about the location')),
            ],
        ),
    ]
