# Generated by Django 5.2.8 on 2025-11-14 03:01

from django.db import migrations


def remove_duplicate_attendance_records(apps, schema_editor):
    """
    Remove duplicate AttendanceRecord entries.
    Keep the most recently created record for each (meeting, student) pair.
    """
    AttendanceRecord = apps.get_model('activity', 'AttendanceRecord')

    # Find all duplicate pairs
    from django.db.models import Count
    duplicates = (
        AttendanceRecord.objects
        .values('meeting', 'student')
        .annotate(count=Count('id'))
        .filter(count__gt=1)
    )

    # For each duplicate pair, keep only the most recent record
    for dup in duplicates:
        records = (
            AttendanceRecord.objects
            .filter(meeting=dup['meeting'], student=dup['student'])
            .order_by('-id')  # Most recent first (assuming auto-incrementing IDs)
        )

        # Delete all but the first (most recent) record
        records_to_delete = list(records)[1:]
        for record in records_to_delete:
            record.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0020_location'),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_attendance_records, migrations.RunPython.noop),
        # Add unique constraint to prevent future duplicates
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('meeting', 'student')},
        ),
    ]
