# Generated by Django 5.2.8 on 2025-11-14 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0021_remove_duplicate_attendance_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='activity.organization'),
            preserve_default=False,
        ),
    ]
