# Generated by Django 5.2.8 on 2025-11-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0022_location_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='max_capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of students (advisory only)', null=True),
        ),
    ]
