# Generated by Django 5.2.8 on 2025-11-16 21:10
import os
import django.db.models.deletion
from django.db import migrations, models

def forwards_func(apps, schema_editor):
    """
    Conditionally migrates location data based on an environment variable.
    - In 'PRODUCTION' mode, points all activities to Location ID 1.
    - In 'development' mode (default), intelligently normalizes and links
      locations to preserve existing dev data.
    """
    Activity = apps.get_model('activity', 'Activity')
    Location = apps.get_model('activity', 'Location')
    db_alias = schema_editor.connection.alias
    
    strategy = os.environ.get('ZUMBAMAIL_MIGRATION_STRATEGY', 'DEVELOPMENT')

    if strategy.upper() == 'PRODUCTION':
        # --- PRODUCTION LOGIC ---
        # If the canonical location (ID=1) exists, point all activities to it.
        if Location.objects.using(db_alias).filter(id=1).exists():
            Activity.objects.using(db_alias).update(location='1')
        # If ID 1 doesn't exist, this does nothing, which is safe.

    else:
        # --- DEVELOPMENT LOGIC ---
        # This logic is safe for existing dev DBs and new dev DBs.
        for activity in Activity.objects.using(db_alias).select_related('session__organization').all():
            location_name = activity.location
            
            if not location_name or not isinstance(location_name, str) or not location_name.strip():
                continue

            org = activity.session.organization
            
            # Normalize names to prevent creating duplicates
            canonical_name = location_name.strip()
            if org.name == "Rochester Rec Dept":
                if canonical_name.lower() in ["my bedroom", "our bedroom"]:
                    canonical_name = "Our Bedroom"
                elif canonical_name.lower() in ["ice arena", "rochester ice arena"]:
                    canonical_name = "Rochester Ice Arena"
            
            # Use get_or_create to safely find or create the location
            location_obj, created = Location.objects.using(db_alias).get_or_create(
                name=canonical_name,
                organization=org
            )
            
            activity.location = str(location_obj.id)
            activity.save(update_fields=['location'])


def reverse_func(apps, schema_editor):
    """
    Reverts location data from ForeignKey back to CharField names.
    """
    Activity = apps.get_model('activity', 'Activity')
    db_alias = schema_editor.connection.alias

    for activity in Activity.objects.using(db_alias).select_related('location').all():
        if activity.location:
            activity.location = activity.location.name
            activity.save(update_fields=['location'])


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0023_activity_max_capacity'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
        migrations.AlterField(
            model_name='activity',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='activity.location'),
        ),
    ]
