# Generated by Django 5.2.8 on 2026-09-13 21:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0024_alter_activity_location_and_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='waitlist_rank',
            field=models.PositiveIntegerField(blank=True, help_text='Optional waitlist priority (1 = first). Null means unranked.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'waiting'), ('waitlist_rank__isnull', False)), fields=('activity', 'waitlist_rank'), name='unique_waitlist_rank_per_activity'),
        ),
    ]
